[build]
  command = "bun install && bunx turbo build"
  publish = "web/tradecraft-web/dist/public"
[functions]
  included_files = ["web/tradecraft-web/private/**"]
  directory = "web/tradecraft-web/netlify-functions"
